-- HREmployment
select 
	DistrictID,
	rtrim(DistrictAbbrev) as District,
	DistrictTitle
from tblDistrict

select
	(select DistrictId from tblDistrict) as OrgId,
	te.SocSecNo as SSNumId,
	te.EmployeeID as EmpId,
	te.FName as NameFirst,
	te.Nickname as NameFirstPreferred,
	te.LName as NameLast,
	te.PreviousLastName as NameLastPrevious,
	te.MI as NameMiddle,
	null as NamePrefix,
	null as NameSuffix,
	(case when isnull(te.Gender, '') = '' then 'U' else te.Gender end) as GenderCode,
	te.HomeAddress as HomeAddrStreet,
	te.HomeCity as HomeAddrCity,
	te.HomeState as HomeAddrStateCode,
	te.HomeZip as HomeAddrZip,
	null as HomeAddrForeignStateCode,
	te.Phone as HomePhone,
	null as HomePhoneMobile,
	ad.Address1 + rtrim(isnull(ad.Address2,'')) as MailAddrStreet,
	ad.City as MailAddrCity,
	ad.[State] as MailAddrStateCode,
	ad.Zip as MailAddrZip,
	null as MailAddrForeignStateCode,
	te.HomeEmail as EmailHome,
	te.Email as EmailWork,
	null as EmailAddrOpt,
	null as EmailPINOpt,
	(select top 1 PhoneNumber from tblPhone where EmployeeID = te.EmployeeID and PhoneTypeID = 2) as WorkPhone,
	(select top 1 Extension from tblPhone where EmployeeID = te.EmployeeID and PhoneTypeID = 2) as WorkPhoneExt,
	(select top 1 PhoneNumber from tblPhone where EmployeeID = te.EmployeeID and PhoneTypeID = 3) as WorkPhoneMobile,
	te.EmplNo as EmpNum,
	(select top 1 [Name] from tblEmergencyContact where ecEmployeeID = te.EmployeeID) as EmergencyContact,
	(select top 1 Phone from tblEmergencyContact where ecEmployeeID = te.EmployeeID) as EmergencyContactPhone,
	null as EmergencyContactPhoneExt,
	(select top 1 ect.[Type] from tblEmergencyContact ct inner join DS_Global..tblEmergencyContactType ect on ect.EmergencyContactTypeID = ct.ContactTypeID and ct.ecEmployeeID = te.EmployeeID ) as EmergencyContactRelationship,
	null as EmergencyDoctor,
	null as EmergencyDoctorPhone,
	null as EmergencyDoctorPhoneExt,
	null as SpouseDateBirth,
	null as SpouseName,
	null as SpousePhone,
	null as SpousePhoneExt,
	null as SpouseSSNum,
	cl.ClassDescription as PersonTypeId,
	null as AcademicDeptCode,
	null as CBestCode,
	null as DateCBest,
	(case when exists(select * from tblActionDue where adEmployeeID = te.EmployeeID and ActionTypeID in (select ActionTypeID from tblActionType where (TypeDesc like '%cpr%' or TypeDesc like '%c.p.r.%' or TypeDesc like '%c p r%'))) then 1 else null end) as CPRCertRqd,
	null as DateAnniv,
	(CONVERT(VARCHAR(10), te.DOB, 110)) as DateBirth,
	null as DateChangeBenefits,
	null as DateCobraExpires,
	null as DateCPRCertExpires,
	null as DateDOJClearance,
	null as DateDriversLicenseExpiration,
	null as DateEligibleBenefits,
	null as DateExperienceBase,
	null as DateFBIClearance,
	null as FingerPrinted,
	null as FingerprintTypeCode,
	null as DateFingerprinted,
	null as FingerprintComment,
	null as DateFirstAidCertExpires,
	null as HepBRqd,
	null as DateHepBCompleted,
	null as DateHepBNotification1,
	null as DateHepBNotification2,
	null as DateHepBWaiver,
	null as Rehire,
	CONVERT(VARCHAR(10), te.hiredate, 110) as DateHired,
	null as DateRehired,
	null as I9StatusCode,
	null as DateI9Status,
	null as Insurance,
	null as DateInsuranceExpires,
	null as DateLeaveBaseOverride,
	null as DateLongevity,
	null as NLIReason,
	null as NLIRqd,
	null as DateNLIReported,
	null as PermanencyCode,
	null as DatePermanency,
	(CONVERT(VARCHAR(10), te.ClassRetirementDate, 110)) as DatePERSRetirement,
	null as PhysicalTestCode,
	null as DatePhysicalTest,
	null as DateProbationEnds,
	null as SeniorityRank,
	null as DateSeniority,
	(CONVERT(VARCHAR(10), te.CertRetirementDate , 110)) as DateSTRSRetirement,
	null as TbTestTypeCode,
	(select top 1 CONVERT(VARCHAR(10), ad2.DateLast, 110) from tblActionDue ad2 where ad2.adEmployeeID = te.employeeid and ActionTypeID in (select ActionTypeID from tblActionType where TypeDesc like '%TB%')) as DateTB,
	null as TerminationCode,
	(CONVERT(VARCHAR(10), te.TerminateDate, 110)) as DateTermination,
	null as DateTerminationLastDay,
	null as DateTerminationLastPaycheck,
	null as DateVisaExpiration,
	null as DriversLicenseNum,
	null as DriversLicenseRqd,
	null as EmpDirCode,
	null as EmpDirReleaseCode,
	(select st.[Status] from tblEmployee te02 inner join tblStatus st on st.StatusID = te02.StatusID and te02.EmployeeID = te.EmployeeID) as EmploymentStatusCode,
	null as EmploymentTypeCode,
	te.IsHispanic EthnicityHispanicBased,
	null as EthnicityCode,
	null as EthnicityCode1,
	null as EthnicityCode2,
	null as EthnicityCode3,
	null as EthnicityCode4,
	null as ExperienceYearsAdj,
	null as ExperienceYearsInState,
	null as ExperienceYearsOutState,
	null as ExperienceYearsPrior,
	(case when exists(select * from tblActionDue where adEmployeeID = te.EmployeeID and ActionTypeID in (select ActionTypeID from tblActionType where (TypeDesc like '%first aid%'))) then 1 else null end) asFirstAidCertRqd,
	null as ForeignStateCode,
	null as HasMultiplePos,
	null as KioskAccessEnabled,
	null as LanguageCode,
	null as LeaveGroupCodeOverride,
	null as MailStopCode,
	null as MilitaryCode,
	null as CoachCertRqd,
	null as DateCoachCertEffective,
	null as ConcussionCertRqd,
	null as DateConcussionCertEffective,
	null as SCATrainingRqd,
	null as DateSCATrainingExpires,
	null as DateTerminationPrevious,
	null as InfluenzaRqd,
	null as DateInfluenza,
	null as MeaslesRqd,
	null as DateMeasles,
	null as PertussisRqd,
	null as DatePertussis
from tblEmployee te
left join
	[Address] ad
	on te.MailingAddressId = ad.Id
left join
	tblClassifications cl
	on cl.ClassificationID = te.ClassificationId

